### ISSUE TITLE
Code Review: 25 November 2021

### ISSUE THREAD

**Issue by CRClothier** [ShadyShawkat/awesome-books#5]
Hi Shady,

Great work on your project so far! 👍 I particularly like how you've implemented the time which continuously updates.

- This is not really a code problem but perhaps you could improve the user experience by adding some text to the book list when there are no books added yet, such as, 'no data in the library'.
- Another nice feature to include could be some kind of alert or popup when you submit the add book button.

But these are really just small things and I really like what you have done with your project so far!

**Comment by gabrie-lhilarion** [comment]
Nice one Shady.

**Comment by ShadyShawkat** [comment]
Thank you @CRClothier and @gabrie-lhilarion for the great feedback. 🙏🏻 

I'll be sure to implement these changes as soon as possible.
