### ISSUE TITLE
2021-11-30 Peer-to-peer code review

### ISSUE THREAD

**Issue by vechicin** [ShadyShawkat/awesome-books#6]
# Hi @ShadyShawkat , awesome job! 💯 💪 🔥 ✅ 🤓 
I really liked your project as a whole, and I particularly enjoyed the clock implementation and the alert window once you add a book!

## Things to consider to make your project even better

https://github.com/ShadyShawkat/awesome-books/blob/d7e7fd9c66559156a54fe474d0dfbc49ca4a5c73/index.html#L43-L44

- [ ] It would be nice to use some custom form validation with a custom error message instead of just adding the "required" attribute in the HTML input tag

https://github.com/ShadyShawkat/awesome-books/blob/d7e7fd9c66559156a54fe474d0dfbc49ca4a5c73/index.html#L7

- [ ] It would make your page look more professional if you changed the title from "Document" to "Awesome Books" or any other title you see fit and included an icon for it

## Once again, awesome job! I found your page to be very impressive! Keep it up 😄

**Comment by franklinben23** [comment]
I found the project very professionally written, features were implemented as required and in an efficient manner, congrats!

The only thing that could be changed going forward is the way the codebase is arranged, dividing it into files to give it more modularity and ease of reading.

**Comment by ShadyShawkat** [comment]
# Hi @vechicin and @franklinben23👋🏻 

I'll definitely consider making these changes in the project and my upcoming projects too. 
Thank you for taking the time to go through my project. I really appreciate it.

**Comment by gdumani** [comment]
*Nice Job Shady, fantasic project!!*

- I like the clean look of it with nice details.
- Code is clean, I agree on the comment by other reviewers about splitting the classes in different files.(I do "mistake" when developing, since it is easier for me to keep all the information in one place ... ;) )
- Clock is nice.
- I would add some validation to avoid adding the same book multiple times, at least in contiguous transactions.

**Comment by ShadyShawkat** [comment]
# Hi @gdumani,

Thanks for the feedback. I agree with your suggestions. I'll be sure to implement a validation to avoid repeating book names.
